### ISSUE TITLE
fetch_all_prs() broken in csv_database.py

### ISSUE THREAD

**Issue by foolip** [foolip/ecosystem-infra-stats#9]
Trying to run build.sh with a new virtualenv setup, this happens today:
```
chromium import stats...
Read 2564 PRs from wpt-prs.csv
Fetching new PRs
Fetching page 1
No more new PRs
Fetched 2600 PRs created and merged after 2017-07-01T00:00:00Z
Writing file wpt-prs.csv
Traceback (most recent call last):
  File "wpt-import-stats.py", line 194, in <module>
    main()
  File "wpt-import-stats.py", line 186, in main
    pr_db = fetch_all_prs()
  File "/usr/local/google/home/foolip/src/ecosystem-infra-stats/wpt_common.py", line 136, in fetch_all_prs
    pr_db.write(order='asc')
  File "/usr/local/google/home/foolip/src/ecosystem-infra-stats/csv_database.py", line 45, in write
    for key in sorted(self.entry_by_id.keys()):
TypeError: unorderable types: int() < str()
```

@Hexcles FYI

**Comment by foolip** [comment]
I'm guessing that the reason I haven't seen this before is because of Python 3.5 vs. 3.6. I have 3.6 on my Mac, but 3.5 on the Linux machine where I got this failure. There are more failures too.

**Comment by foolip** [comment]
Yeah, commit 7b2b80c24c6eee8980d43fed8576a30f1b4a5b1a actually makes no sense, because wpt-usage-stats needs py2. I'll switch to Python 2 and document it.
